root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/devdeck.exe ."
  bin = "./tmp/devdeck.exe"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "json"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_dir = []
  exclude_file = []
  delay = 1000 # ms
  stop_on_error = true
  log = "air_errors.log"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
